(async function(){
  const $=s=>document.querySelector(s), $$=s=>[...document.querySelectorAll(s)];
  const esc=s=>String(s??'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const loadJson=(globalName,file)=>window[globalName]||fetch(file).then(r=>r.json());
  const [DB,TEMPLATES,REPORTS]=await Promise.all([
    loadJson('BNT_DATA','data.json'),
    loadJson('BNT_TEMPLATES','templates.json'),
    loadJson('BNT_REPORTS','report-data.json')
  ]);
  const root=$('#app'), modal=$('#modal-root'), toastRoot=$('#toast-root'), fileInput=$('#template-import');
  const MONTHS=['Янв','Фев','Мар','Апр','Май','Июн','Июл','Авг','Сен','Окт','Ноя','Дек'];
  const MONTHS_FULL=['Январь','Февраль','Март','Апрель','Май','Июнь','Июль','Август','Сентябрь','Октябрь','Ноябрь','Декабрь'];
  const KIND_NAMES={metrics:'Ключевые показатели',cf:'Денежные потоки (CF)',fi:'Финансовые показатели',ai:'Баланс',ci:'CAPEX',production:'Pelogas — производственные данные'};
  const latestCf2026={
    'Начальный остаток':[6374176.61,7031165.71,7358085.24,7086835.76,7258870.18,7078935.63,8381036.21,null,null,null,null,null],
    'Конечный остаток':[7031165.71,7358085.24,7086835.76,7258870.18,7078935.63,8381036.21,8843443.24,null,null,null,null,null],
    'Net cash flows':[656989.10,326919.53,-271249.48,172034.42,-179934.55,1302100.58,462407.03,null,null,null,null,null],
    '+ от опер.':[2387922.66,1483117.70,1207926.74,2273425.87,1789783.72,2495486.88,2177152.99,null,null,null,null,null],
    '- от опер.':[-1450927.07,-987190.91,-1420489.26,-1880756.25,-1954057.92,-1809254.19,-1955083.98,null,null,null,null,null],
    '+ от инвест.':[null,null,null,null,null,472536.20,475900.40,null,null,null,null,null],
    '- от инвест.':[-293527.21,-183859.16,-61102.45,-231301.89,-16217.80,-125277.84,-237896.68,null,null,null,null,null],
    '+ от фин.':[13520.72,14851.90,2415.49,10666.69,557.45,268609.53,2334.30,null,null,null,null,null],
    'CAPEX':[-293527.21,-183859.16,-61102.45,-231301.89,-16217.80,-125277.84,-237896.68,null,null,null,null,null],
    'Dividends':[null,null,null,null,null,472536.20,475900.40,null,null,null,null,null],
    'Доходы от %':[21505.10,20202.45,24977.60,21169.06,24296.19,23747.33,27894.13,null,null,null,null,null],
    'Доходы от аренды':[1160.28,9803.34,17785.63,8815.66,3012.22,16031.13,9330.60,null,null,null,null,null],
    'Доходы от неосн.':[14058.90,15962.56,2415.49,10868.27,2498.01,270504.76,3923.49,null,null,null,null,null],
    'Курсовая разница':[-248.96,-363.19,-12259.31,-187.17,-2.97,-0.03,0,null,null,null,null,null],
    'Пенсионный фонд':[-32196.48,-13988.88,-27158.60,-16337.20,-21888.28,-18505.98,-17071.96,null,null,null,null,null],
    'Платежи поставщикам':[-797798.67,-737875.36,-730072.35,-1008827.72,-1211948.59,-1125975.65,-1183198.99,null,null,null,null,null],
    'ФОТ':[-479577.68,-665215.10,-525336.34,-722844.31,-561751.45,-535583.55,-622405.64,null,null,null,null,null],
    'Платежи в бюджет':[-118432.65,-111911.07,-109805.64,-111263.58,-117625.89,-112841.35,-113851.99,null,null,null,null,null],
    'Прочие платежи':[-22672.63,542162.69,-15857.02,-21296.27,-40840.74,-16347.63,-18555.40,null,null,null,null,null]
  };

  const blockCatalog={
    transshipment:{title:'Поступления за перевалку',kind:'cf',type:'barTable',size:'half'},
    inflow:{title:'Структура поступлений',kind:'cf',type:'barTable',size:'half'},
    netflow:{title:'Динамика чистых денежных потоков',kind:'cf',type:'columnTable',size:'half'},
    outflow:{title:'Структура выбытий',kind:'cf',type:'barTable',size:'half'},
    waterfall:{title:'Отчет о движении денежных средств',kind:'cf',type:'waterfall',size:'full'},
    kpi:{title:'Ключевые показатели',kind:'metrics',type:'kpi',size:'full'},
    metricTrend:{title:'Динамика выручки и EBITDA',kind:'metrics',type:'line',size:'half'},
    planFact:{title:'План / факт — ключевые показатели',kind:'metrics',type:'planFact',size:'half'},
    finance:{title:'Финансовые показатели',kind:'fi',type:'genericTable',size:'full'},
    operations:{title:'Операционная аналитика',kind:'fi',type:'genericTable',size:'full'},
    balance:{title:'Баланс — ключевые статьи',kind:'ai',type:'genericTable',size:'full'},
    liquidity:{title:'Ликвидность и финансовые коэффициенты',kind:'metrics',type:'genericTable',size:'half'},
    capex:{title:'CAPEX — инвестиционная программа',kind:'ci',type:'capex',size:'full'},
    general_oil:{title:'Объем перевалки нефтеналивных грузов',kind:'production',type:'compare',size:'half',seed:'general.general_oil'},
    general_oil_dry:{title:'Нефтеналивные и сухие грузы',kind:'production',type:'compare',size:'half',seed:'general.general_oil_dry'},
    general_total_cargo:{title:'Общий объем перевалки',kind:'production',type:'compare',size:'full',seed:'general.general_total_cargo'},
    general_net_profit:{title:'Чистая прибыль',kind:'metrics',type:'compare',size:'third',seed:'general.general_net_profit'},
    general_ebitda:{title:'EBITDA',kind:'metrics',type:'compare',size:'third',seed:'general.general_ebitda'},
    general_margin:{title:'EBITDA margin',kind:'metrics',type:'compare',size:'third',seed:'general.general_margin'},
    general_cogs:{title:'Себестоимость',kind:'fi',type:'compare',size:'third',seed:'general.general_cogs'},
    general_oar:{title:'ОАР',kind:'fi',type:'compare',size:'third',seed:'general.general_oar'},
    general_capex:{title:'Капитальные вложения',kind:'ci',type:'compare',size:'third',seed:'general.general_capex'},
    is_income:{title:'Доходы',kind:'fi',type:'compare',size:'half',seed:'is.is_income'},
    is_core_income:{title:'Доходы от основной деятельности',kind:'fi',type:'compare',size:'half',seed:'is.is_core_income'},
    is_transshipment:{title:'Доход от перевалки грузов',kind:'fi',type:'compare',size:'full',seed:'is.is_transshipment'},
    is_expenses:{title:'Расходы',kind:'fi',type:'compare',size:'full',seed:'is.is_expenses'},
    is_cogs:{title:'Себестоимость',kind:'fi',type:'compare',size:'half',seed:'is.is_cogs'},
    is_oar:{title:'ОАР',kind:'fi',type:'compare',size:'half',seed:'is.is_oar'},
    cons_production:{title:'Производственные показатели',kind:'production',type:'matrix',size:'full',seed:'consolidated.cons_production'},
    cons_finance:{title:'Финансово-экономические показатели',kind:'fi',type:'matrix',size:'full',seed:'consolidated.cons_finance'},
    cons_capex:{title:'Капитальные вложения',kind:'ci',type:'matrix',size:'half',seed:'consolidated.cons_capex'},
    cons_payroll:{title:'Фонд оплаты труда и численность',kind:'metrics',type:'matrix',size:'half',seed:'consolidated.cons_payroll'}
  };

  const state={
    view:'reports',activeTemplateId:'cf-main',source:1,year:2026,monthFrom:1,monthTo:7,currency:'USD',unit:'thousand',
    blocks:['transshipment','inflow','netflow','outflow','waterfall'],editLayout:false,showTables:true,showCodes:false,
    overrides:{},templateOverrides:{},seedOverrides:{},manualLog:[],customTemplates:[],customBlocks:{},schedules:[],dataKind:'metrics'
  };
  try{const s=JSON.parse(localStorage.getItem('bnt-studio-v5')||'null');if(s)Object.assign(state,s)}catch(e){}
  const persist=()=>localStorage.setItem('bnt-studio-v5',JSON.stringify(state));
  const srcName=id=>({1:'БНТ',2:'БМП',3:'Консолидация'}[id]||id);
  const divider=()=>state.unit==='raw'?1:state.unit==='million'?1e6:1e3;
  const fx=()=>state.currency==='GEL'?2.68:1;
  const conv=v=>Number(v||0)*fx()/divider();
  const unitLabel=()=>state.unit==='raw'?(state.currency==='USD'?'$':'₾'):state.unit==='million'?(state.currency==='USD'?'млн $':'млн ₾'):(state.currency==='USD'?'тыс. $':'тыс. ₾');
  const fmt=(v,d=state.unit==='raw'?0:0)=>v==null?'—':new Intl.NumberFormat('ru-RU',{minimumFractionDigits:d,maximumFractionDigits:d}).format(conv(v));
  const fmtSeed=(v,unit='')=>v==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:unit==='%'?1:0}).format(v)+(unit==='%'?'%':'');
  const fmtRaw=v=>v==null?'—':new Intl.NumberFormat('ru-RU',{maximumFractionDigits:2}).format(Number(v));
  const pct=v=>Number.isFinite(v)?`${v>=0?'+':''}${new Intl.NumberFormat('ru-RU',{maximumFractionDigits:1}).format(v)}%`:'—';
  const norm=s=>String(s||'').trim().toLowerCase().replace(/\s+/g,' ');
  const activeTemplate=()=>[...TEMPLATES,...state.customTemplates].find(t=>t.id===state.activeTemplateId)||null;
  const reportTitle=()=>activeTemplate()?.reportTitle||activeTemplate()?.name||`Управленческий отчет — ${srcName(state.source)}`;
  const sourceLabel=()=>activeTemplate()?.sourceLabel||'1С / Управленческая отчетность';
  const currentTemplateKey=()=>state.activeTemplateId||'draft';

  const icon=(name,cls='')=>{const p={
    reports:'<rect x="4" y="4" width="16" height="16" rx="2"/><path d="M8 15V9M12 15v-3M16 15V7"/>',templates:'<path d="M6 4h9l3 3v13H6z"/><path d="M15 4v4h4M9 12h6M9 16h6"/>',builder:'<path d="M4 7h10M4 12h16M4 17h10"/><circle cx="18" cy="7" r="2"/><circle cx="8" cy="17" r="2"/>',data:'<ellipse cx="12" cy="6" rx="7" ry="2.5"/><path d="M5 6v6c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5V6M5 12v6c0 1.4 3.1 2.5 7 2.5s7-1.1 7-2.5v-6"/>',sync:'<path d="M20 6v5h-5M4 18v-5h5"/><path d="M7 9a7 7 0 0 1 11-2l2 4M17 15a7 7 0 0 1-11 2l-2-4"/>',schedule:'<rect x="4" y="5" width="16" height="15" rx="2"/><path d="M8 3v4M16 3v4M4 9h16M12 12v4l3 1"/>',add:'<path d="M12 5v14M5 12h14"/>',edit:'<path d="M4 20h4l10-10-4-4L4 16zM13 7l4 4"/>',save:'<path d="M5 5h12l2 2v12H5zM8 5v5h7V5M8 17h8"/>',import:'<path d="M12 4v11m-4-4 4 4 4-4M5 20h14"/>',export:'<path d="M12 20V9m-4 4 4-4 4 4M5 4h14"/>',print:'<path d="M7 8V4h10v4M7 17H5a2 2 0 0 1-2-2v-4a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2v4a2 2 0 0 1-2 2h-2M7 14h10v6H7z"/>',excel:'<path d="M5 4h10l4 4v12H5zM15 4v4h4M8 11l5 6M13 11l-5 6"/>',chart:'<path d="M5 19V9M10 19V5M15 19v-7M20 19V8"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M12 3v2M12 19v2M3 12h2M19 12h2M5.6 5.6 7 7M17 17l1.4 1.4M18.4 5.6 17 7M7 17l-1.4 1.4"/>',close:'<path d="M6 6l12 12M18 6 6 18"/>',drag:'<circle cx="8" cy="7" r="1"/><circle cx="8" cy="12" r="1"/><circle cx="8" cy="17" r="1"/><circle cx="16" cy="7" r="1"/><circle cx="16" cy="12" r="1"/><circle cx="16" cy="17" r="1"/>',share:'<circle cx="18" cy="5" r="2"/><circle cx="6" cy="12" r="2"/><circle cx="18" cy="19" r="2"/><path d="M8 11l8-5M8 13l8 5"/>',history:'<path d="M4 12a8 8 0 1 0 3-6M4 4v5h5M12 8v5l3 2"/>',check:'<path d="m5 12 4 4 10-10"/>',mail:'<rect x="3" y="5" width="18" height="14" rx="2"/><path d="m4 7 8 6 8-6"/>',chev:'<path d="m9 6 6 6-6 6"/>'};return `<svg class="ico ${cls}" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="1.7" stroke-linecap="round" stroke-linejoin="round">${p[name]||''}</svg>`};

  function datasets(kind,basis='actual'){return DB.datasets.filter(d=>d.source===Number(state.source)&&d.year===Number(state.year)&&d.kind===kind&&d.basis===basis)}
  function dataset(kind,basis='actual'){return datasets(kind,basis)[0]||null}
  function rows(kind,basis='actual'){
    const d=dataset(kind,basis);if(!d)return[];
    if(basis==='plan'){const plans=[...new Set(d.rows.map(r=>r.plan_version).filter(Boolean))];const pv=plans[0];return d.rows.filter(r=>!r.plan_version||r.plan_version===pv)}
    return d.rows;
  }
  function findRow(kind,key,basis='actual'){const rr=rows(kind,basis);let r=rr.find(x=>norm(x.code)===norm(key))||rr.find(x=>norm(x.name)===norm(key));if(!r)r=rr.find(x=>norm(x.name).includes(norm(key))||norm(key).includes(norm(x.name)));return r||null}
  function sourceOverrideKey(d,row,m){return `${d.key}|${row.id}|${m}`}
  function rawMonth(kind,row,m,basis='actual'){
    if(!row)return null;const d=dataset(kind,basis);if(!d)return null;const k=sourceOverrideKey(d,row,m);if(k in state.overrides)return Number(state.overrides[k]);
    if(basis==='actual'&&Number(state.source)===1&&Number(state.year)===2026&&kind==='cf'){const v=latestCf2026[row.name];if(v&&v[m-1]!=null)return v[m-1]}
    return row.values?.[m-1]??null;
  }
  function aggregate(kind,row,basis='actual'){
    if(!row)return 0;const n=norm(row.name);
    if(kind==='cf'&&n.includes('начальный остаток')){for(let m=state.monthFrom;m<=state.monthTo;m++){const v=rawMonth(kind,row,m,basis);if(v!=null)return v}return 0}
    if(kind==='cf'&&n.includes('конечный остаток')){for(let m=state.monthTo;m>=state.monthFrom;m--){const v=rawMonth(kind,row,m,basis);if(v!=null)return v}return 0}
    let s=0;for(let m=state.monthFrom;m<=state.monthTo;m++){const v=rawMonth(kind,row,m,basis);if(v!=null)s+=v}return s;
  }
  const agg=(kind,key,basis='actual')=>aggregate(kind,findRow(kind,key,basis),basis);
  const plan=(kind,key)=>{const r=findRow(kind,key,'plan');return r?aggregate(kind,r,'plan'):null};
  function templateVal(blockId,key,base){const t=state.templateOverrides[currentTemplateKey()]?.[blockId];return t&&Object.prototype.hasOwnProperty.call(t,key)?Number(t[key]):base}
  function setTemplateVal(blockId,key,value){const tid=currentTemplateKey();state.templateOverrides[tid]??={};state.templateOverrides[tid][blockId]??={};state.templateOverrides[tid][blockId][key]=Number(value)}
  function seedBlock(blockId){const meta=blockCatalog[blockId]||state.customBlocks[blockId];if(!meta?.seed)return null;const [group,key]=meta.seed.split('.');return REPORTS[group]?.blocks?.[key]||null}
  function seedValue(blockId,r,s,base){const t=state.seedOverrides[currentTemplateKey()]?.[blockId];const key=`${r}:${s}`;return t&&Object.prototype.hasOwnProperty.call(t,key)?Number(t[key]):base}
  function setSeedValue(blockId,r,s,value){const tid=currentTemplateKey();state.seedOverrides[tid]??={};state.seedOverrides[tid][blockId]??={};state.seedOverrides[tid][blockId][`${r}:${s}`]=Number(value)}
  function getBlockMeta(id){return blockCatalog[id]||state.customBlocks[id]||{title:id,kind:'metrics',type:'unknown',size:'half'}}

  function shell(content,title){
    const nav=[['reports','reports','Отчеты'],['templates','templates','Шаблоны'],['builder','builder','Конструктор'],['data','data','Данные'],['schedules','schedule','Рассылки'],['sync','sync','Синхронизация']];
    return `<div class="app"><aside class="sidebar"><div class="brand"><svg viewBox="0 0 114 29"><use href="#Logo"></use></svg></div><div class="nav-label">Управленческая отчетность</div><nav>${nav.map(([v,i,l])=>`<button class="nav-item ${state.view===v?'active':''}" data-nav="${v}">${icon(i)}<span>${l}</span></button>`).join('')}</nav><div class="nav-label">Система</div><nav><button class="nav-item" data-action="reset-demo">${icon('sync')}<span>Сбросить демо</span></button></nav><div class="sidebar-foot"><div class="avatar">ДБ</div><div><b>Демо-пользователь</b><small>Администратор отчетности</small></div></div></aside><main><header><div class="crumbs"><span>ITP Portal</span><span>/</span><span>Управленческая отчетность</span><span>/</span><b>${esc(title)}</b></div><div class="header-actions"><span class="sync-dot"></span><small>1С + Pelogas · данные доступны</small><button class="btn small" data-action="sync">${icon('sync')}Синхронизировать</button></div></header><div class="content">${content}</div></main></div>`;
  }
  function pageHead(title,desc,actions=''){return `<div class="page-head"><div><h1>${esc(title)}</h1><p>${desc}</p></div><div class="actions">${actions}</div></div>`}
  function filters(){return `<div class="filterbar"><label>Компания<select data-filter="source"><option value="1" ${state.source===1?'selected':''}>БНТ</option><option value="2" ${state.source===2?'selected':''}>БМП</option><option value="3" ${state.source===3?'selected':''}>Консолидация</option></select></label><label>Год<select data-filter="year">${[2024,2025,2026].map(y=>`<option ${state.year===y?'selected':''}>${y}</option>`).join('')}</select></label><label>Период<div class="period"><select data-filter="monthFrom">${MONTHS_FULL.map((m,i)=>`<option value="${i+1}" ${state.monthFrom===i+1?'selected':''}>${m}</option>`).join('')}</select><span>—</span><select data-filter="monthTo">${MONTHS_FULL.map((m,i)=>`<option value="${i+1}" ${state.monthTo===i+1?'selected':''}>${m}</option>`).join('')}</select></div></label><label>Валюта<select data-filter="currency"><option ${state.currency==='USD'?'selected':''}>USD</option><option ${state.currency==='GEL'?'selected':''}>GEL</option></select></label><label>Единица<select data-filter="unit"><option value="raw" ${state.unit==='raw'?'selected':''}>ед.</option><option value="thousand" ${state.unit==='thousand'?'selected':''}>тыс.</option><option value="million" ${state.unit==='million'?'selected':''}>млн</option></select></label><div class="filter-source"><b>${esc(activeTemplate()?.name||'Черновик')}</b><span>${esc(sourceLabel())}</span></div></div>`}
  const empty=text=>`<div class="empty">${esc(text)}</div>`;

  function reportBlock(id){
    const b=getBlockMeta(id);let body='';
    if(b.type==='compare')body=compareBlock(id);
    else if(b.type==='matrix')body=matrixBlock(id);
    else if(b.type==='indicatorLine'||b.type==='indicatorColumn')body=indicatorBlock(id,b);
    else if(b.type==='seedIndicator')body=seedIndicatorBlock(id,b);
    else if(id==='transshipment'){const d=cfTransshipment(id);body=barChart(d)+dataTable(id,d,'Всего',d.reduce((s,x)=>s+x.value,0));}
    else if(id==='inflow'){const d=cfInflow(id);body=barChart(d)+dataTable(id,d,'Всего',d.reduce((s,x)=>s+x.value,0));}
    else if(id==='netflow'){const d=monthlyNet(id);body=barChart(d,{horizontal:false})+dataTable(id,d,'Итого',d.reduce((s,x)=>s+x.value,0));}
    else if(id==='outflow'){const d=cfOutflow(id);body=barChart(d)+dataTable(id,d,'Всего',d.reduce((s,x)=>s+x.value,0));}
    else if(id==='waterfall')body=waterfall(id);
    else if(id==='kpi')body=kpiBlock(id);
    else if(id==='metricTrend'){const s=['Выручка','EBITDA'].map(k=>{const r=findRow('metrics',k);return r?{name:r.name,values:Array.from({length:12},(_,i)=>templateVal(id,`${r.code}:${i+1}`,rawMonth('metrics',r,i+1)))}:null}).filter(Boolean);body=lineChart(s)}
    else if(id==='planFact')body=planFactBlock(id);
    else if(id==='finance')body=genericTable(id,'fi',['BIHL0574','BIHL0590','BIHL0577','BIHL0578','BIHL0575','BIHL0579']);
    else if(id==='operations')body=genericTable(id,'fi',['BIHL0590','BIHL1348','BIHL1344','BIHL1346','BIHL1350','BIHL1354']);
    else if(id==='balance')body=genericTable(id,'ai',['1','2','85','21','97','102']);
    else if(id==='liquidity')body=genericTable(id,'metrics',['КоэффициентТекущейЛиквидности','КоэффициентБыстройЛиквидности','КоэффициентДенежнойЛиквидности','СоотношениеДолгаККапиталу']);
    else if(id==='capex')body=capexBlock(id);else body=empty('Блок пока не настроен');
    return `<section class="report-block size-${b.size||'half'}" draggable="${state.editLayout}" data-block="${id}"><div class="block-head"><div class="block-title-wrap">${state.editLayout?`<span class="drag">${icon('drag')}</span>`:''}<div><h3>${esc(b.title)}</h3><span>${esc(b.kind==='production'?'Pelogas':KIND_NAMES[b.kind]||'Отчет')} · ${esc(seedBlock(id)?.unit||unitLabel())}</span></div></div><div class="block-actions"><button class="icon-btn" data-action="block-excel" data-id="${id}" title="Excel">${icon('excel')}</button><button class="icon-btn" data-action="block-pdf" data-id="${id}" title="PDF">${icon('print')}</button>${state.editLayout?`<button class="icon-btn" data-action="remove-block" data-id="${id}" title="Удалить">${icon('close')}</button>`:''}</div></div><div class="block-body">${body}</div></section>`;
  }

  function barChart(data,{horizontal=true}={}){
    if(!data.length)return empty('Нет данных для выбранного среза');
    if(horizontal){const mx=Math.max(...data.map(x=>Math.abs(x.value)),1);return `<div class="hchart">${data.map(x=>`<div class="hrow"><div class="hname" title="${esc(x.name)}">${esc(x.name)}</div><div class="htrack"><span class="hbar ${x.value<0?'negative-bar':''}" style="width:${Math.max(1,Math.abs(x.value)/mx*100)}%"></span></div><div class="hval">${fmt(x.value)}</div></div>`).join('')}</div>`}
    const vals=data.map(x=>x.value??0),min=Math.min(0,...vals),max=Math.max(0,...vals),range=max-min||1;return `<div class="vchart">${data.map(x=>{const h=Math.max(3,Math.abs(x.value)/range*78);return `<div class="vcol"><div class="vvalue">${fmt(x.value)}</div><div class="vplot"><span class="vbar ${x.value<0?'neg':''}" style="height:${h}%"></span></div><div class="vname">${esc(x.name)}</div></div>`}).join('')}</div>`;
  }
  function lineChart(series){
    if(!series.length)return empty('Нет данных');const idx=[];for(let m=state.monthFrom;m<=state.monthTo;m++)idx.push(m-1);const vals=series.flatMap(s=>idx.map(i=>s.values[i]).filter(v=>v!=null));if(!vals.length)return empty('Нет данных');
    const W=760,H=260,p={l:50,r:18,t:16,b:36},min=Math.min(0,...vals),max=Math.max(0,...vals),range=max-min||1,x=i=>p.l+(i/Math.max(1,idx.length-1))*(W-p.l-p.r),y=v=>p.t+(max-v)/range*(H-p.t-p.b);
    const grids=[0,.25,.5,.75,1].map(t=>{const yy=p.t+t*(H-p.t-p.b);return `<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}"/><text x="${p.l-8}" y="${yy+4}" text-anchor="end">${fmt(max-t*range)}</text>`}).join('');
    const paths=series.map((s,si)=>{const pts=idx.map((mi,i)=>s.values[mi]==null?null:[x(i),y(s.values[mi])]).filter(Boolean);const d=pts.map((q,i)=>(i?'L':'M')+q[0]+','+q[1]).join(' ');return `<path d="${d}" class="line l${si}"/>${pts.map(q=>`<circle cx="${q[0]}" cy="${q[1]}" r="3" class="point p${si}"/>`).join('')}`}).join('');
    return `<div class="svgchart"><svg viewBox="0 0 ${W} ${H}"><g class="grid">${grids}</g>${idx.map((mi,i)=>`<text class="xlabel" x="${x(i)}" y="${H-10}" text-anchor="middle">${MONTHS[mi]}</text>`).join('')}${paths}</svg><div class="legend">${series.map((s,i)=>`<span><i class="ldot l${i}"></i>${esc(s.name)}</span>`).join('')}</div></div>`;
  }
  function dataTable(blockId,data,totalLabel='Всего',total=null){if(!state.showTables)return'';return `<div class="mini-table"><table><thead><tr><th>Показатель</th><th>${unitLabel()}</th></tr></thead><tbody>${total!=null?`<tr class="total"><td>${esc(totalLabel)}</td><td>${fmt(total)}</td></tr>`:''}${data.map((x,i)=>`<tr><td>${esc(x.name)}</td><td class="num template-edit" data-template-edit data-block-id="${blockId}" data-value-key="${esc(x.key||x.name)}" data-value-label="${esc(x.name)}" data-base="${Number(x.value)}">${fmt(x.value)}</td></tr>`).join('')}</tbody></table></div>`}

  function cfTransshipment(blockId){return rows('cf').filter(r=>String(r.code).startsWith('Перевалка_')).map(r=>({name:r.name.replace(/^Перевалка[_\s-]*/i,''),key:r.code,value:templateVal(blockId,r.code,aggregate('cf',r))})).filter(x=>Math.abs(x.value)>0.0001).sort((a,b)=>b.value-a.value)}
  function cfInflow(blockId){const base=[{name:'Перевалка',value:cfTransshipment(blockId).reduce((s,x)=>s+x.value,0)},{name:'Дивиденды',value:agg('cf','Dividends')},{name:'Прочие доходы',value:agg('cf','Прочие доходы')},{name:'Доходы от неосн.',value:agg('cf','Доходы от неосн.')},{name:'Доходы от аренды',value:agg('cf','Доходы от аренды')},{name:'Доходы от %',value:agg('cf','Доходы от %')}];return base.map(x=>({...x,key:x.name,value:templateVal(blockId,x.name,x.value)})).filter(x=>Math.abs(x.value)>0.0001)}
  function cfOutflow(blockId){const base=[{name:'CAPEX',value:-agg('cf','CAPEX')},{name:'Платежи поставщикам',value:-agg('cf','Платежи поставщикам')},{name:'ФОТ',value:-agg('cf','ФОТ')},{name:'Платежи в бюджет',value:-agg('cf','Платежи в бюджет')},{name:'Курсовая разница',value:-agg('cf','Курсовая разница')},{name:'Пенсионный фонд',value:-agg('cf','Пенсионный фонд')},{name:'Прочие платежи',value:-agg('cf','Прочие платежи')}];return base.map(x=>({...x,key:x.name,value:templateVal(blockId,x.name,x.value)}))}
  function monthlyNet(blockId){const r=findRow('cf','Net cash flows');return Array.from({length:state.monthTo-state.monthFrom+1},(_,i)=>{const m=state.monthFrom+i,base=rawMonth('cf',r,m);return {name:MONTHS[m-1],key:`m${m}`,value:templateVal(blockId,`m${m}`,base)}})}

  function compareBlock(blockId){
    const seed=seedBlock(blockId);if(!seed)return empty('Нет контрольных данных');const group=getBlockMeta(blockId).seed.split('.')[0];const series=REPORTS[group]?.series||seed.headers||[];
    const vals=seed.rows.map((r,ri)=>({name:r.name,values:r.values.map((v,si)=>seedValue(blockId,ri,si,v))}));
    return compareChart(vals,series,seed.unit)+compareTable(blockId,vals,series,seed.unit);
  }
  function compareChart(rowsData,series,unit){
    if(!rowsData.length)return empty('Нет данных');const palette=['#72a9d7','#f39a56','#a9afb5','#63ad7a','#8f82c9'];const max=Math.max(...rowsData.flatMap(r=>r.values.map(v=>Math.max(0,Number(v)||0))),1);const n=rowsData.length,sc=series.length,W=Math.max(620,n*96),H=260,p={l:46,r:18,t:24,b:55},plotW=W-p.l-p.r,groupW=plotW/n,barW=Math.min(20,(groupW-12)/Math.max(1,sc));
    const y=v=>p.t+(1-(Math.max(0,v)/max))*(H-p.t-p.b);const grid=[0,.25,.5,.75,1].map(t=>{const yy=p.t+t*(H-p.t-p.b),v=max*(1-t);return `<line x1="${p.l}" y1="${yy}" x2="${W-p.r}" y2="${yy}" class="cmp-grid"/><text x="${p.l-7}" y="${yy+3}" text-anchor="end" class="cmp-axis">${new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(v)}</text>`}).join('');
    const bars=rowsData.map((r,ri)=>r.values.map((v,si)=>{const x=p.l+ri*groupW+(groupW-sc*barW)/2+si*barW,yv=y(v),h=Math.max(1,H-p.b-yv);return `<rect x="${x}" y="${yv}" width="${Math.max(5,barW-3)}" height="${h}" rx="1" fill="${palette[si%palette.length]}"><title>${esc(r.name)} · ${esc(series[si]||'')}: ${fmtSeed(v,unit)}</title></rect><text x="${x+(barW-3)/2}" y="${Math.max(10,yv-4)}" text-anchor="middle" class="cmp-value">${Math.abs(v)>=1000?new Intl.NumberFormat('ru-RU',{notation:'compact',maximumFractionDigits:1}).format(v):fmtSeed(v,unit)}</text>`}).join('')+`<text x="${p.l+ri*groupW+groupW/2}" y="${H-31}" text-anchor="middle" class="cmp-label">${esc(r.name.length>18?r.name.slice(0,17)+'…':r.name)}</text>`).join('');
    return `<div class="compare-chart-scroll"><svg class="compare-chart" viewBox="0 0 ${W} ${H}" style="min-width:${W}px">${grid}${bars}</svg></div><div class="compare-legend">${series.map((s,i)=>`<span><i style="background:${palette[i%palette.length]}"></i>${esc(s)}</span>`).join('')}</div>`;
  }
  function compareTable(blockId,rowsData,series,unit){if(!state.showTables)return'';return `<div class="wide-table compare-table"><table><thead><tr><th>Показатель</th>${series.map(s=>`<th class="num">${esc(s)}</th>`).join('')}</tr></thead><tbody>${rowsData.map((r,ri)=>`<tr><td>${esc(r.name)}</td>${r.values.map((v,si)=>`<td class="num seed-edit" data-seed-edit data-block-id="${blockId}" data-row-index="${ri}" data-series-index="${si}" data-value-label="${esc(r.name+' · '+(series[si]||''))}" data-base="${Number(v)}">${fmtSeed(v,unit)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}
  function matrixBlock(blockId){const seed=seedBlock(blockId);if(!seed)return empty('Нет данных');const headers=seed.headers||[];const vals=seed.rows.map((r,ri)=>({name:r.name,values:r.values.map((v,si)=>seedValue(blockId,ri,si,v))}));return `<div class="wide-table matrix-table"><table><thead><tr><th>Показатель</th>${headers.map(h=>`<th class="num">${esc(h)}</th>`).join('')}</tr></thead><tbody>${vals.map((r,ri)=>`<tr><td>${esc(r.name)}</td>${r.values.map((v,si)=>`<td class="num seed-edit" data-seed-edit data-block-id="${blockId}" data-row-index="${ri}" data-series-index="${si}" data-value-label="${esc(r.name+' · '+(headers[si]||''))}" data-base="${Number(v)}">${fmtSeed(v,seed.unit)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`}

  function indicatorBlock(id,b){const r=findRow(b.kind,b.rowKey);if(!r)return empty('Показатель не найден');const values=Array.from({length:12},(_,i)=>templateVal(id,`${r.code}:${i+1}`,rawMonth(b.kind,r,i+1)));const ser=[{name:r.name,values}];const body=b.type==='indicatorColumn'?barChart(Array.from({length:state.monthTo-state.monthFrom+1},(_,i)=>({name:MONTHS[state.monthFrom+i-1],value:values[state.monthFrom+i-1]})),{horizontal:false}):lineChart(ser);const table=state.showTables?`<div class="mini-table"><table><thead><tr><th>Месяц</th><th>${unitLabel()}</th></tr></thead><tbody>${Array.from({length:state.monthTo-state.monthFrom+1},(_,i)=>{const m=state.monthFrom+i,v=values[m-1];return `<tr><td>${MONTHS_FULL[m-1]}</td><td class="num template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(r.code+':'+m)}" data-value-label="${esc(r.name+' · '+MONTHS_FULL[m-1])}" data-base="${Number(v||0)}">${fmt(v)}</td></tr>`}).join('')}</tbody></table></div>`:'';return body+table}
  function seedIndicatorBlock(id,b){const source=seedBlock(b.sourceBlockId);if(!source)return empty('Нет данных');const row=source.rows[b.rowIndex];if(!row)return empty('Показатель не найден');const group=getBlockMeta(b.sourceBlockId).seed.split('.')[0],series=REPORTS[group]?.series||source.headers||[];const vals=row.values.map((v,si)=>seedValue(b.sourceBlockId,b.rowIndex,si,v));return compareChart([{name:row.name,values:vals}],series,source.unit)+compareTable(b.sourceBlockId,[{name:row.name,values:vals}],series,source.unit)}

  function kpiBlock(id){const keys=[['Выручка','Выручка'],['EBITDA','EBITDA'],['ЧистаяПрибыль','Чистая прибыль'],['ОперационнаяПрибыль','Операционная прибыль'],['ВаловыйДоход','Валовый доход']];return `<div class="kpi-grid">${keys.map(([k,l])=>{const base=agg('metrics',k),a=templateVal(id,k,base),p=plan('metrics',k),v=p?(a-p)/Math.abs(p)*100:null;return `<div class="kpi-card template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(k)}" data-value-label="${esc(l)}" data-base="${Number(a)}"><span>${l}</span><strong>${fmt(a)}</strong><small class="${v!=null&&v<0?'neg-txt':'pos-txt'}">${v==null?unitLabel():pct(v)+' к плану'}</small></div>`}).join('')}</div>`}
  function planFactBlock(id){const keys=['Выручка','EBITDA','ЧистаяПрибыль','ОперационнаяПрибыль'];return `<div class="wide-table"><table><thead><tr><th>Показатель</th><th>Факт</th><th>План</th><th>Отклонение</th><th>Исполнение</th></tr></thead><tbody>${keys.map(k=>{const r=findRow('metrics',k);if(!r)return'';const a=templateVal(id,k,aggregate('metrics',r)),p=plan('metrics',k),v=p?(a-p)/Math.abs(p)*100:null,exec=p?Math.min(100,Math.abs(a/p)*100):0;return `<tr><td>${esc(r.name)}</td><td class="num template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(k)}" data-value-label="${esc(r.name)}" data-base="${Number(a)}">${fmt(a)}</td><td class="num">${p==null?'—':fmt(p)}</td><td class="num ${v<0?'neg-txt':'pos-txt'}">${v==null?'—':pct(v)}</td><td><div class="progress"><span style="width:${exec}%"></span></div></td></tr>`}).join('')}</tbody></table></div>`}
  function genericTable(id,kind,keys){const rr=keys.map(k=>findRow(kind,k)).filter(Boolean);if(!rr.length)return empty('Нет данных для выбранного среза');return `<div class="wide-table"><table><thead><tr><th>Показатель</th><th>${MONTHS[state.monthTo-1]}</th><th>Период</th><th>План</th><th>Δ</th></tr></thead><tbody>${rr.map(r=>{const base=aggregate(kind,r),a=templateVal(id,r.code,base),m=rawMonth(kind,r,state.monthTo),p=plan(kind,r.code),v=p?(a-p)/Math.abs(p)*100:null;return `<tr><td>${esc(r.name)}${state.showCodes?`<small>${esc(r.code)}</small>`:''}</td><td class="num">${fmt(m)}</td><td class="num template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(r.code)}" data-value-label="${esc(r.name)}" data-base="${Number(a)}">${fmt(a)}</td><td class="num">${p==null?'—':fmt(p)}</td><td class="num ${v<0?'neg-txt':'pos-txt'}">${v==null?'—':pct(v)}</td></tr>`}).join('')}</tbody></table></div>`}
  function capexBlock(id){const rr=rows('ci').map(r=>({r,a:aggregate('ci',r)})).filter(x=>Math.abs(x.a)>0).sort((a,b)=>Math.abs(b.a)-Math.abs(a.a)).slice(0,10);if(!rr.length)return empty('CAPEX недоступен');return `<div class="wide-table capex"><table><thead><tr><th>Проект / статья</th><th>Исполнитель</th><th>Факт</th><th>План</th><th>Δ</th></tr></thead><tbody>${rr.map(({r,a:base})=>{const a=templateVal(id,r.code,base),p=plan('ci',r.code),v=p?(a-p)/Math.abs(p)*100:null;return `<tr><td>${esc(r.name)}</td><td>${esc(r.performer_name||r.performer||'—')}</td><td class="num template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(r.code)}" data-value-label="${esc(r.name)}" data-base="${Number(a)}">${fmt(a)}</td><td class="num">${p==null?'—':fmt(p)}</td><td class="num ${v!=null&&v>0?'neg-txt':'pos-txt'}">${v==null?'—':pct(v)}</td></tr>`}).join('')}</tbody></table></div>`}
  function waterfall(id){const base=[{name:'Начальный остаток',value:agg('cf','Начальный остаток'),kind:'base'},{name:'+ от опер.',value:agg('cf','+ от опер.'),kind:'plus'},{name:'- от опер.',value:agg('cf','- от опер.'),kind:'minus'},{name:'+ от инвест.',value:agg('cf','+ от инвест.'),kind:'plus'},{name:'- от инвест.',value:agg('cf','- от инвест.'),kind:'minus'},{name:'+ от фин.',value:agg('cf','+ от фин.'),kind:'plus'},{name:'- от фин.',value:0,kind:'minus'},{name:'Other',value:0,kind:'other'},{name:'Конечный остаток',value:agg('cf','Конечный остаток'),kind:'base'}];const d=base.map(x=>({...x,value:templateVal(id,x.name,x.value)}));let running=d[0].value,points=[{start:0,end:running,...d[0]}];for(let i=1;i<d.length-1;i++){const start=running;running+=d[i].value;points.push({start,end:running,...d[i]})}points.push({start:0,end:d[d.length-1].value,...d[d.length-1]});const mx=Math.max(...points.flatMap(x=>[x.start,x.end]).map(Math.abs),1),H=250;const chart=`<div class="waterfall"><div class="wfchart">${points.map(p=>{const top=Math.max(p.start,p.end),bottom=Math.min(p.start,p.end),height=Math.max(2,(top-bottom)/mx*82),offset=bottom/mx*82;return `<div class="wfcol"><div class="wfvalue">${fmt(p.value)}</div><div class="wfplot"><span class="wfbar ${p.kind}" style="height:${height}%;bottom:${offset}%"></span></div><div class="wfname">${esc(p.name)}</div></div>`}).join('')}</div></div>`;const table=state.showTables?`<div class="mini-table"><table><thead><tr><th>Показатель</th><th>${unitLabel()}</th></tr></thead><tbody>${d.map(x=>`<tr><td>${esc(x.name)}</td><td class="num template-edit" data-template-edit data-block-id="${id}" data-value-key="${esc(x.name)}" data-value-label="${esc(x.name)}" data-base="${Number(x.value)}">${fmt(x.value)}</td></tr>`).join('')}</tbody></table></div>`:'';return chart+table}

  function reportPage(){const actions=`<button class="btn" data-action="toggle-tables">${state.showTables?'Скрыть таблицы':'Показать таблицы'}</button><button class="btn" data-action="toggle-layout">${icon('edit')}${state.editLayout?'Завершить редактирование':'Редактировать макет'}</button><button class="btn" data-action="add-block">${icon('add')}Добавить блок</button><button class="btn" data-action="report-excel">${icon('excel')}Excel</button><button class="btn" data-action="schedule-current">${icon('mail')}Автоотправка</button><button class="btn primary" data-action="print">${icon('print')}PDF / Печать</button>`;return shell(`${pageHead('Отчеты','Каждый шаблон открывает собственную форму, период и источник данных. Значения можно корректировать в рамках конкретного шаблона без изменения исходного набора.',actions)}${filters()}<div class="paper"><div class="paper-title"><div><h2>${esc(reportTitle())}</h2><small>${esc(activeTemplate()?.description||'')}</small></div><span>${esc(srcName(state.source))} · ${esc(sourceLabel())}</span></div><div class="report-grid">${state.blocks.map(reportBlock).join('')}</div><div class="paper-foot"><span>ООО «Батумский нефтяной терминал»</span><span>Powered by ITP Portal</span></div></div>`, 'Отчеты')}
  function templatesPage(){const all=[...TEMPLATES,...state.customTemplates];return shell(`${pageHead('Шаблоны','Готовые формы открываются со своими реальными контрольными данными, периодом и источником. Их можно копировать, редактировать, выгружать и назначать на автоматическую рассылку.',`<button class="btn" data-action="import-template">${icon('import')}Принять JSON</button><button class="btn primary" data-action="save-template">${icon('save')}Сохранить текущий</button>`)}<div class="templates">${all.map((t,i)=>`<article class="template"><div class="template-top"><span class="tag">${esc(t.tag||'Личный')}</span><div><button class="icon-btn" data-action="schedule-template" data-index="${i}" title="Рассылка">${icon('mail')}</button><button class="icon-btn" data-action="share-template" data-index="${i}" title="JSON">${icon('share')}</button></div></div><h3>${esc(t.name)}</h3><p>${esc(t.description||'Пользовательский шаблон')}</p><div class="template-meta"><span>${esc(t.sourceLabel||'1С')}</span><span>${t.filters?.year||state.year}</span></div><div class="template-mock">${(t.blocks||[]).slice(0,8).map(b=>`<i class="${getBlockMeta(b).size==='full'?'wide':getBlockMeta(b).size==='third'?'third':''}"></i>`).join('')}</div><div class="template-bottom"><span>${(t.blocks||[]).length} блоков</span><button class="btn small" data-action="open-template" data-index="${i}">Открыть ${icon('chev')}</button></div></article>`).join('')}</div>`, 'Шаблоны')}
  function builderPage(){const dynamic=Object.entries(blockCatalog).filter(([id,b])=>!b.seed);return shell(`${pageHead('Конструктор','Соберите новую форму из готовых блоков или создайте отдельный график по любому показателю. Рабочая область остается широкой — настройки открываются отдельно.',`<button class="btn" data-action="create-chart">${icon('chart')}График по показателю</button><button class="btn" data-action="preview">Предпросмотр</button><button class="btn primary" data-action="save-template">${icon('save')}Сохранить шаблон</button>`)}${filters()}<div class="builder-layout"><aside class="catalog"><h3>Библиотека блоков</h3><p>Финансовые, производственные и контрольные представления.</p>${dynamic.map(([id,b])=>`<button class="catalog-item" data-action="catalog-add" data-id="${id}"><div><b>${esc(b.title)}</b><small>${esc(KIND_NAMES[b.kind]||'Отчет')} · ${esc(b.type)}</small></div>${icon('add')}</button>`).join('')}<h3 class="catalog-section-title">Готовые формы</h3>${['general_oil','general_oil_dry','general_total_cargo','is_income','is_expenses','cons_production','cons_finance'].map(id=>{const b=getBlockMeta(id);return `<button class="catalog-item" data-action="catalog-add" data-id="${id}"><div><b>${esc(b.title)}</b><small>${esc(b.kind==='production'?'Pelogas':KIND_NAMES[b.kind])}</small></div>${icon('add')}</button>`}).join('')}</aside><section class="canvas"><div class="canvas-head"><div><h3>Холст отчета</h3><p>Перетаскивайте блоки. Индивидуальные графики сохраняются вместе с шаблоном.</p></div><button class="btn" data-action="add-block">${icon('add')}Добавить блок</button></div><div class="canvas-grid">${state.blocks.map(id=>{const b=getBlockMeta(id);return `<div class="canvas-block" draggable="true" data-canvas-block="${id}"><span class="drag">${icon('drag')}</span><div><b>${esc(b.title)}</b><small>${esc(b.size==='full'?'На всю ширину':b.size==='third'?'1/3 страницы':'1/2 страницы')}</small></div><button class="icon-btn" data-action="remove-block" data-id="${id}">${icon('close')}</button></div>`}).join('')}</div></section></div>`, 'Конструктор')}

  function dataPage(){const dbKinds=['metrics','cf','fi','ai','ci'].filter(k=>dataset(k));const kinds=['production',...dbKinds];const kind=state.dataKind&&kinds.includes(state.dataKind)?state.dataKind:kinds[0];state.dataKind=kind;if(kind==='production')return productionDataPage(kinds);const rr=rows(kind).slice(0,100);return shell(`${pageHead('Данные','Исходные значения из 1С. Для каждого показателя можно сразу построить отдельный график или изменить конкретный месяц с обязательным комментарием.',`<button class="btn" data-action="history">${icon('history')}История изменений</button>`)}${filters()}<div class="data-layout"><aside class="dataset-list">${kinds.map(k=>`<button class="dataset-item ${k===kind?'active':''}" data-action="select-kind" data-kind="${k}"><span>${esc(KIND_NAMES[k])}</span><em>${k==='production'?REPORTS.general.blocks.general_total_cargo.rows.length:rows(k).length}</em></button>`).join('')}</aside><div class="data-card"><div class="data-head"><h3>${esc(KIND_NAMES[kind])}</h3><span>${srcName(state.source)} · Факт · ${state.year}</span></div><div class="data-scroll"><table><thead><tr><th>Код / показатель</th><th>График</th>${MONTHS.map(m=>`<th>${m}</th>`).join('')}<th>Период</th></tr></thead><tbody>${rr.map(r=>`<tr><td>${esc(r.name)}${state.showCodes?`<small>${esc(r.code)}</small>`:''}</td><td><button class="icon-btn inline" data-action="chart-row" data-kind="${kind}" data-row="${esc(r.id)}" title="Создать график">${icon('chart')}</button></td>${MONTHS.map((m,i)=>`<td class="num editable" data-source-edit data-kind="${kind}" data-row="${esc(r.id)}" data-month="${i+1}">${fmt(rawMonth(kind,r,i+1))}</td>`).join('')}<td class="num total-cell">${fmt(aggregate(kind,r))}</td></tr>`).join('')}</tbody></table></div></div></div>`, 'Данные')}
  function productionDataPage(kinds){const seed=REPORTS.general.blocks.general_total_cargo,series=REPORTS.general.series;return shell(`${pageHead('Данные','Производственные данные представлены отдельным источником Pelogas. В демо используются реальные значения из предоставленной формы «Общие показатели».',`<button class="btn" data-action="create-chart">${icon('chart')}Новый график</button>`)}<div class="integration-strip"><div><span class="status ok">Подключено</span><b>Pelogas</b><small>Производственные объемы, виды грузов, тарифные показатели</small></div><div><b>Последняя синхронизация</b><small>28.08.2026 15:50</small></div></div><div class="data-layout"><aside class="dataset-list">${kinds.map(k=>`<button class="dataset-item ${k==='production'?'active':''}" data-action="select-kind" data-kind="${k}"><span>${esc(KIND_NAMES[k])}</span><em>${k==='production'?seed.rows.length:rows(k).length}</em></button>`).join('')}</aside><div class="data-card"><div class="data-head"><h3>Pelogas — производственные показатели</h3><span>Контрольный срез · 8 мес 2026</span></div><div class="data-scroll"><table class="production-table"><thead><tr><th>Показатель</th><th>График</th>${series.map(s=>`<th class="num">${esc(s)}</th>`).join('')}</tr></thead><tbody>${seed.rows.map((r,ri)=>`<tr><td>${esc(r.name)}</td><td><button class="icon-btn inline" data-action="chart-seed-row" data-source-block="general_total_cargo" data-row-index="${ri}" title="Создать график">${icon('chart')}</button></td>${r.values.map((v,si)=>`<td class="num seed-edit" data-seed-edit data-block-id="general_total_cargo" data-row-index="${ri}" data-series-index="${si}" data-value-label="${esc(r.name+' · '+series[si])}" data-base="${v}">${fmtSeed(seedValue('general_total_cargo',ri,si,v),seed.unit)}</td>`).join('')}</tr>`).join('')}</tbody></table></div></div></div>`, 'Данные')}

  function schedulesPage(){const all=[...TEMPLATES,...state.customTemplates];return shell(`${pageHead('Автоматические рассылки','Настройте ежедневную, еженедельную или ежемесячную отправку выбранного шаблона на e-mail. В демо расписания сохраняются локально; на backend это подключается к SMTP/очереди задач.',`<button class="btn primary" data-action="new-schedule">${icon('add')}Новая рассылка</button>`)}<div class="schedule-summary"><div><b>${state.schedules.filter(s=>s.enabled).length}</b><span>активных</span></div><div><b>${state.schedules.length}</b><span>всего правил</span></div><div><b>${new Set(state.schedules.flatMap(s=>s.recipients||[])).size}</b><span>получателей</span></div></div><div class="schedule-list">${state.schedules.length?state.schedules.map((s,i)=>{const t=all.find(x=>x.id===s.templateId);return `<article class="schedule-card"><div class="schedule-status"><span class="status ${s.enabled?'ok':''}">${s.enabled?'Активна':'Пауза'}</span><button class="icon-btn" data-action="delete-schedule" data-index="${i}">${icon('close')}</button></div><h3>${esc(t?.name||s.templateId)}</h3><p>${esc(s.frequencyLabel)} · ${esc(s.time)} · ${esc(s.format)}</p><div class="schedule-recipients">${(s.recipients||[]).map(x=>`<span>${esc(x)}</span>`).join('')}</div><div class="schedule-actions"><button class="btn small" data-action="test-schedule" data-index="${i}">${icon('mail')}Тестовая отправка</button><button class="btn small" data-action="toggle-schedule" data-index="${i}">${s.enabled?'Приостановить':'Включить'}</button></div></article>`}).join(''):empty('Рассылки еще не настроены')}</div>`, 'Рассылки')}
  function syncPage(){const snaps=DB.datasets.filter(d=>d.source===Number(state.source)&&d.year===Number(state.year));return shell(`${pageHead('Синхронизация','Контролируемая загрузка финансовых данных из 1С и производственных данных из Pelogas. Ручные корректировки шаблонов сохраняются отдельно от исходных данных.',`<button class="btn primary" data-action="sync">${icon('sync')}Запустить синхронизацию</button>`)}${filters()}<div class="integration-grid"><div class="integration-card"><div class="integration-head"><span class="status ok">Подключено</span><b>1С</b></div><h3>Финансовые данные</h3><p>CF, IS, баланс, CAPEX, KPI, планы и фактические значения.</p><div class="integration-stats"><span>${snaps.length} наборов</span><span>${snaps.reduce((s,d)=>s+d.rows.length,0)} строк</span></div></div><div class="integration-card"><div class="integration-head"><span class="status ok">Подключено</span><b>Pelogas</b></div><h3>Производственные данные</h3><p>Объем перевалки, типы грузов и производственные показатели.</p><div class="integration-stats"><span>${REPORTS.general.blocks.general_total_cargo.rows.length} показателей</span><span>контроль 8 мес 2026</span></div></div></div><div class="sync-layout"><div class="sync-card hero"><span class="status ok">Актуально</span><strong>${snaps.length+1}</strong><h3>источников и наборов</h3><p>${srcName(state.source)} · ${state.year} · ручных корректировок: ${state.manualLog.length}</p><div class="sync-metrics"><div><b>${snaps.reduce((s,d)=>s+d.rows.length,0)}</b><span>строк 1С</span></div><div><b>${REPORTS.general.blocks.general_total_cargo.rows.length}</b><span>Pelogas KPI</span></div><div><b>${state.schedules.filter(s=>s.enabled).length}</b><span>рассылки</span></div><div><b>${state.manualLog.length}</b><span>корректировки</span></div></div></div><div class="sync-card"><h3>Последние срезы</h3>${snaps.slice().sort((a,b)=>String(b.timestamp).localeCompare(String(a.timestamp))).slice(0,6).map(d=>`<div class="snapshot"><i></i><div><b>${esc(d.kindName)} · ${esc(d.basisName)}</b><span>${esc(d.timestamp)} · ${d.rows.length} строк</span></div></div>`).join('')}<div class="snapshot"><i></i><div><b>Pelogas · производственные данные</b><span>28.08.2026 15:50 · контрольный срез</span></div></div></div></div>`, 'Синхронизация')}

  function applyTemplate(t){if(!t)return;state.activeTemplateId=t.id;state.blocks=[...(t.blocks||[])];if(t.filters)Object.assign(state,t.filters);if(t.customBlocks)Object.assign(state.customBlocks,t.customBlocks);state.view='reports';render();toast('Шаблон открыт',t.name)}
  function render(){if(state.monthFrom>state.monthTo)state.monthFrom=state.monthTo;root.innerHTML=state.view==='reports'?reportPage():state.view==='templates'?templatesPage():state.view==='builder'?builderPage():state.view==='data'?dataPage():state.view==='schedules'?schedulesPage():syncPage();bindDrag();persist()}
  function toast(title,text=''){const d=document.createElement('div');d.className='toast';d.innerHTML=`<span>${icon('check')}</span><div><b>${esc(title)}</b>${text?`<small>${esc(text)}</small>`:''}</div>`;toastRoot.appendChild(d);setTimeout(()=>d.remove(),3000)}

  function blockModal(){modal.innerHTML=`<div class="overlay" data-close><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>Добавить блок</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><div class="block-picker">${Object.entries(blockCatalog).map(([id,b])=>`<button data-action="modal-add-block" data-id="${id}"><div class="block-icon">${icon(b.kind==='production'?'chart':b.kind==='cf'?'reports':b.kind==='ci'?'builder':'data')}</div><div><b>${esc(b.title)}</b><span>${esc(b.kind==='production'?'Pelogas':KIND_NAMES[b.kind]||'Отчет')} · ${b.size==='full'?'полная ширина':b.size==='third'?'1/3 страницы':'1/2 страницы'}</span></div></button>`).join('')}</div></div></div></div>`}
  function saveTemplateModal(){modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Сохранить шаблон</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><label class="field">Название<input id="tpl-name" value="Копия — ${esc(activeTemplate()?.name||'Управленческий отчет')}"></label><label class="field">Описание<textarea id="tpl-desc">${state.blocks.length} блоков · ${MONTHS[state.monthFrom-1]}–${MONTHS[state.monthTo-1]} ${state.year}</textarea></label><label class="field">Доступ<select id="tpl-tag"><option>Личный</option><option>ПЭО</option><option>Общий</option></select></label></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="confirm-save">Сохранить</button></div></div></div>`}
  function templateEditModal(blockId,key,label,base){modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Корректировка в шаблоне</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><h4>${esc(label)}</h4><div class="compare"><div><span>Расчетное значение</span><b>${fmtRaw(base)}</b></div><div><span>Область изменения</span><b>${esc(activeTemplate()?.name||'Черновик')}</b></div></div><label class="field">Новое значение<input id="tpl-edit-value" value="${Number(base)}"></label><label class="field">Причина<textarea id="tpl-edit-reason" placeholder="Уточнение / корректировка для конкретной формы"></textarea></label><p class="modal-note">Исходные данные 1С/Pelogas не изменяются. Корректировка действует только в текущем шаблоне и попадет в историю.</p></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="save-template-edit" data-block-id="${blockId}" data-value-key="${esc(key)}" data-value-label="${esc(label)}" data-base="${Number(base)}">Сохранить</button></div></div></div>`}
  function seedEditModal(blockId,ri,si,label,base){modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Корректировка в шаблоне</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><h4>${esc(label)}</h4><div class="compare"><div><span>Исходное значение формы</span><b>${fmtRaw(base)}</b></div><div><span>Шаблон</span><b>${esc(activeTemplate()?.name||'Черновик')}</b></div></div><label class="field">Новое значение<input id="seed-edit-value" value="${Number(base)}"></label><label class="field">Причина<textarea id="seed-edit-reason" placeholder="Комментарий к корректировке"></textarea></label><p class="modal-note">Изменение сохраняется только для данного шаблона и автоматически перестраивает график.</p></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="save-seed-edit" data-block-id="${blockId}" data-row-index="${ri}" data-series-index="${si}" data-value-label="${esc(label)}" data-base="${Number(base)}">Сохранить</button></div></div></div>`}
  function sourceEditModal(kind,rowId,m){const d=dataset(kind),r=d?.rows.find(x=>x.id===rowId);if(!r)return;const cur=rawMonth(kind,r,m),orig=r.values?.[m-1];modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Ручная корректировка исходных данных</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><h4>${esc(r.name)}</h4><div class="compare"><div><span>Исходное из 1С</span><b>${fmtRaw(orig)}</b></div><div><span>Действующее</span><b>${fmtRaw(cur)}</b></div></div><label class="field">Новое значение<input id="source-edit-value" value="${cur??''}"></label><label class="field">Причина<textarea id="source-edit-reason" placeholder="Уточнение после закрытия периода"></textarea></label></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="save-source-edit" data-kind="${kind}" data-row="${esc(rowId)}" data-month="${m}">Сохранить</button></div></div></div>`}
  function historyModal(){modal.innerHTML=`<div class="overlay" data-close><div class="modal wide" onclick="event.stopPropagation()"><div class="modal-head"><h3>История изменений</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body">${state.manualLog.length?`<div class="wide-table"><table><thead><tr><th>Дата</th><th>Область</th><th>Показатель</th><th>Было</th><th>Стало</th><th>Причина</th></tr></thead><tbody>${state.manualLog.slice().reverse().map(x=>`<tr><td>${esc(x.date)}</td><td>${esc(x.scope||'Данные')}</td><td>${esc(x.name)}</td><td>${esc(fmtRaw(x.old))}</td><td>${esc(fmtRaw(x.value))}</td><td>${esc(x.reason)}</td></tr>`).join('')}</tbody></table></div>`:empty('Изменений пока нет')}</div></div></div>`}
  function syncModal(){modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Синхронизация источников</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><div class="checklist"><div>${icon('check')}<span><b>1С — срез прошел валидацию</b><small>Источник, период и структура проверены</small></span></div><div>${icon('check')}<span><b>Pelogas — данные доступны</b><small>Производственные показатели готовы к обновлению</small></span></div><div>${icon('check')}<span><b>Корректировки шаблонов защищены</b><small>Не перезаписываются синхронизацией</small></span></div></div></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="confirm-sync">Применить срезы</button></div></div></div>`}
  function chartModal(opts={}){const dbKinds=['metrics','cf','fi','ai','ci'].filter(k=>dataset(k));const kind=opts.kind||dbKinds[0]||'metrics';const rr=rows(kind).slice(0,150);modal.innerHTML=`<div class="overlay" data-close><div class="modal" onclick="event.stopPropagation()"><div class="modal-head"><h3>Создать график по показателю</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><div class="chart-form-grid"><label class="field">Набор данных<select id="chart-kind">${dbKinds.map(k=>`<option value="${k}" ${k===kind?'selected':''}>${esc(KIND_NAMES[k])}</option>`).join('')}</select></label><label class="field">Показатель<select id="chart-row">${rr.map(r=>`<option value="${esc(r.id)}" ${opts.rowId===r.id?'selected':''}>${esc(r.name)}</option>`).join('')}</select></label><label class="field">Тип графика<select id="chart-type"><option value="indicatorLine">Линейный</option><option value="indicatorColumn">Столбчатый</option></select></label><label class="field">Ширина<select id="chart-size"><option value="half">1/2 страницы</option><option value="full">На всю ширину</option><option value="third">1/3 страницы</option></select></label></div><p class="modal-note">График будет добавлен в текущий шаблон и сохранится в JSON-конфигурации.</p></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="confirm-chart">${icon('chart')}Добавить график</button></div></div></div>`;$('#chart-kind')?.addEventListener('change',e=>chartModal({kind:e.target.value}))}
  function seedChartModal(sourceBlockId,rowIndex){const seed=seedBlock(sourceBlockId),row=seed?.rows?.[rowIndex];if(!row)return;modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Добавить график</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><h4>${esc(row.name)}</h4><p class="modal-note">Будет создан отдельный график по реальным сравнительным значениям из производственной формы.</p><label class="field">Название<input id="seed-chart-title" value="${esc(row.name)}"></label><label class="field">Ширина<select id="seed-chart-size"><option value="half">1/2 страницы</option><option value="third">1/3 страницы</option><option value="full">На всю ширину</option></select></label></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="confirm-seed-chart" data-source-block="${sourceBlockId}" data-row-index="${rowIndex}">${icon('chart')}Добавить</button></div></div></div>`}
  function scheduleModal(templateId=state.activeTemplateId){const all=[...TEMPLATES,...state.customTemplates];modal.innerHTML=`<div class="overlay" data-close><div class="modal sm" onclick="event.stopPropagation()"><div class="modal-head"><h3>Автоматическая отправка отчета</h3><button class="icon-btn" data-close>${icon('close')}</button></div><div class="modal-body"><label class="field">Шаблон<select id="schedule-template">${all.map(t=>`<option value="${t.id}" ${t.id===templateId?'selected':''}>${esc(t.name)}</option>`).join('')}</select></label><label class="field">Получатели<input id="schedule-recipients" placeholder="director@company.ge, peo@company.ge"></label><div class="chart-form-grid"><label class="field">Периодичность<select id="schedule-frequency"><option value="daily">Каждый день</option><option value="weekly">Каждую неделю</option><option value="monthly">Каждый месяц</option></select></label><label class="field">Время<input id="schedule-time" type="time" value="08:00"></label><label class="field">Формат<select id="schedule-format"><option>PDF</option><option>Excel</option><option>PDF + Excel</option></select></label><label class="field">Тема письма<input id="schedule-subject" value="Управленческий отчет"></label></div><p class="modal-note">Для промышленной версии правило подключается к SMTP и планировщику задач. В демо конфигурация сохраняется и тестовая отправка имитируется.</p></div><div class="modal-foot"><button class="btn" data-close>Отмена</button><button class="btn primary" data-action="confirm-schedule">${icon('mail')}Сохранить рассылку</button></div></div></div>`}

  function exportTemplate(t){const tid=t?.id||currentTemplateKey();const payload={version:5,id:tid,name:t?.name||activeTemplate()?.name||'BNT report template',reportTitle:t?.reportTitle||reportTitle(),sourceLabel:t?.sourceLabel||sourceLabel(),filters:t?.filters||{source:state.source,year:state.year,monthFrom:state.monthFrom,monthTo:state.monthTo,currency:state.currency,unit:state.unit},blocks:t?.blocks||state.blocks,customBlocks:state.customBlocks,templateOverrides:state.templateOverrides[tid]||{},seedOverrides:state.seedOverrides[tid]||{}};downloadBlob(JSON.stringify(payload,null,2),'application/json','BNT_Report_Template.json')}
  function downloadBlob(content,type,name){const a=document.createElement('a'),url=URL.createObjectURL(new Blob([content],{type}));a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
  function excelHtmlFromElement(el,title){const tables=[...el.querySelectorAll('table')];if(!tables.length)return null;return `<!doctype html><html xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel"><head><meta charset="utf-8"><style>body{font-family:Arial;font-size:11pt}h2{font-size:16pt}table{border-collapse:collapse;margin:14px 0;width:100%}th,td{border:1px solid #d9e3ea;padding:6px}th{background:#eef5f8}td.num{text-align:right}</style></head><body><h2>${esc(title)}</h2>${tables.map(t=>t.outerHTML).join('<br>')}</body></html>`}
  function exportReportExcel(){const old=state.showTables;state.showTables=true;const holder=document.createElement('div');holder.innerHTML=`<div class="paper"><div class="report-grid">${state.blocks.map(reportBlock).join('')}</div></div>`;state.showTables=old;const html=excelHtmlFromElement(holder,reportTitle());if(!html){toast('Нет данных для Excel');return}downloadBlob('\ufeff'+html,'application/vnd.ms-excel',`${safeFileName(activeTemplate()?.name||'BNT_Report')}.xls`);toast('Excel сформирован')}
  function exportBlockExcel(id){const old=state.showTables;state.showTables=true;const holder=document.createElement('div');holder.innerHTML=reportBlock(id);state.showTables=old;const html=excelHtmlFromElement(holder,getBlockMeta(id).title);if(!html){toast('Нет таблицы для экспорта');return}downloadBlob('\ufeff'+html,'application/vnd.ms-excel',`${safeFileName(getBlockMeta(id).title)}.xls`)}
  function printBlock(id){const el=document.querySelector(`[data-block="${CSS.escape(id)}"]`);if(!el)return;const w=window.open('','_blank','width=1100,height=800');if(!w){toast('Разрешите всплывающие окна');return}w.document.write(`<!doctype html><html><head><meta charset="utf-8"><title>${esc(getBlockMeta(id).title)}</title><link rel="stylesheet" href="styles.css"><style>body{background:#fff;padding:20px}.report-block{border:0}.block-actions{display:none}.block-body{padding:10px}</style></head><body>${el.outerHTML}<script>window.onload=()=>setTimeout(()=>window.print(),300)<\/script></body></html>`);w.document.close()}
  const safeFileName=s=>String(s).replace(/[\\/:*?"<>|]+/g,'_').slice(0,80);

  root.addEventListener('click',e=>{
    const nav=e.target.closest('[data-nav]');if(nav){state.view=nav.dataset.nav;render();return}
    const seedCell=e.target.closest('[data-seed-edit]');if(seedCell){seedEditModal(seedCell.dataset.blockId,Number(seedCell.dataset.rowIndex),Number(seedCell.dataset.seriesIndex),seedCell.dataset.valueLabel,Number(seedCell.dataset.base));return}
    const tplCell=e.target.closest('[data-template-edit]');if(tplCell){templateEditModal(tplCell.dataset.blockId,tplCell.dataset.valueKey,tplCell.dataset.valueLabel,Number(tplCell.dataset.base));return}
    const a=e.target.closest('[data-action]');if(!a)return;const ac=a.dataset.action;
    if(ac==='toggle-layout'){state.editLayout=!state.editLayout;render()}
    else if(ac==='toggle-tables'){state.showTables=!state.showTables;render()}
    else if(ac==='add-block')blockModal()
    else if(ac==='remove-block'){state.blocks=state.blocks.filter(x=>x!==a.dataset.id);render()}
    else if(ac==='catalog-add'){if(!state.blocks.includes(a.dataset.id))state.blocks.push(a.dataset.id);toast('Блок добавлен');render()}
    else if(ac==='preview'){state.view='reports';render()}
    else if(ac==='print')window.print()
    else if(ac==='report-excel')exportReportExcel()
    else if(ac==='block-excel')exportBlockExcel(a.dataset.id)
    else if(ac==='block-pdf')printBlock(a.dataset.id)
    else if(ac==='save-template')saveTemplateModal()
    else if(ac==='open-template'){const all=[...TEMPLATES,...state.customTemplates];applyTemplate(all[Number(a.dataset.index)])}
    else if(ac==='share-template'){const all=[...TEMPLATES,...state.customTemplates];exportTemplate(all[Number(a.dataset.index)])}
    else if(ac==='import-template')fileInput.click()
    else if(ac==='select-kind'){state.dataKind=a.dataset.kind;render()}
    else if(ac==='history')historyModal()
    else if(ac==='sync')syncModal()
    else if(ac==='create-chart')chartModal()
    else if(ac==='chart-row'){chartModal({kind:a.dataset.kind,rowId:a.dataset.row})}
    else if(ac==='chart-seed-row')seedChartModal(a.dataset.sourceBlock,Number(a.dataset.rowIndex))
    else if(ac==='schedule-current')scheduleModal()
    else if(ac==='new-schedule')scheduleModal()
    else if(ac==='schedule-template'){const all=[...TEMPLATES,...state.customTemplates];scheduleModal(all[Number(a.dataset.index)]?.id)}
    else if(ac==='test-schedule'){toast('Тестовое письмо сформировано','В промышленной версии будет отправлено через SMTP')}
    else if(ac==='toggle-schedule'){const s=state.schedules[Number(a.dataset.index)];if(s){s.enabled=!s.enabled;render()}}
    else if(ac==='delete-schedule'){state.schedules.splice(Number(a.dataset.index),1);render()}
    else if(ac==='reset-demo'){if(confirm('Сбросить демо и локальные настройки?')){localStorage.removeItem('bnt-studio-v5');location.reload()}}
  });
  root.addEventListener('change',e=>{const f=e.target.dataset.filter;if(f){state[f]=['source','year','monthFrom','monthTo'].includes(f)?Number(e.target.value):e.target.value;state.activeTemplateId='draft';render()}});
  root.addEventListener('click',e=>{const td=e.target.closest('[data-source-edit]');if(td&&state.view==='data')sourceEditModal(td.dataset.kind,td.dataset.row,Number(td.dataset.month))});

  modal.addEventListener('click',e=>{
    if(e.target.closest('[data-close]')){modal.innerHTML='';return}
    const a=e.target.closest('[data-action]');if(!a)return;const ac=a.dataset.action;
    if(ac==='modal-add-block'){if(!state.blocks.includes(a.dataset.id))state.blocks.push(a.dataset.id);modal.innerHTML='';render();toast('Блок добавлен')}
    else if(ac==='confirm-save'){const id='custom-'+Date.now(),t={id,name:$('#tpl-name')?.value||'Новый шаблон',description:$('#tpl-desc')?.value||'',tag:$('#tpl-tag')?.value||'Личный',reportTitle:$('#tpl-name')?.value||'Новый шаблон',sourceLabel:sourceLabel(),filters:{source:state.source,year:state.year,monthFrom:state.monthFrom,monthTo:state.monthTo,currency:state.currency,unit:state.unit},blocks:[...state.blocks],customBlocks:JSON.parse(JSON.stringify(state.customBlocks))};const from=currentTemplateKey();state.customTemplates.push(t);state.templateOverrides[id]=JSON.parse(JSON.stringify(state.templateOverrides[from]||{}));state.seedOverrides[id]=JSON.parse(JSON.stringify(state.seedOverrides[from]||{}));state.activeTemplateId=id;modal.innerHTML='';persist();toast('Шаблон сохранен',t.name)}
    else if(ac==='save-template-edit'){const value=Number(String($('#tpl-edit-value')?.value||'').replace(',','.')),reason=$('#tpl-edit-reason')?.value.trim();if(!Number.isFinite(value)||!reason){toast('Заполните значение и причину');return}setTemplateVal(a.dataset.blockId,a.dataset.valueKey,value);state.manualLog.push({date:new Date().toLocaleString('ru-RU'),scope:`Шаблон: ${activeTemplate()?.name||'Черновик'}`,name:a.dataset.valueLabel,old:Number(a.dataset.base),value,reason});modal.innerHTML='';render();toast('Значение изменено','Только в текущем шаблоне')}
    else if(ac==='save-seed-edit'){const value=Number(String($('#seed-edit-value')?.value||'').replace(',','.')),reason=$('#seed-edit-reason')?.value.trim();if(!Number.isFinite(value)||!reason){toast('Заполните значение и причину');return}setSeedValue(a.dataset.blockId,Number(a.dataset.rowIndex),Number(a.dataset.seriesIndex),value);state.manualLog.push({date:new Date().toLocaleString('ru-RU'),scope:`Шаблон: ${activeTemplate()?.name||'Черновик'}`,name:a.dataset.valueLabel,old:Number(a.dataset.base),value,reason});modal.innerHTML='';render();toast('Значение изменено','График пересчитан автоматически')}
    else if(ac==='save-source-edit'){const kind=a.dataset.kind,d=dataset(kind),r=d?.rows.find(x=>x.id===a.dataset.row),m=Number(a.dataset.month),value=Number(String($('#source-edit-value')?.value||'').replace(',','.')),reason=$('#source-edit-reason')?.value.trim();if(!r||!Number.isFinite(value)||!reason){toast('Заполните значение и причину');return}const key=sourceOverrideKey(d,r,m),old=rawMonth(kind,r,m);state.overrides[key]=value;state.manualLog.push({date:new Date().toLocaleString('ru-RU'),scope:'Исходные данные',name:`${r.name} · ${MONTHS_FULL[m-1]} ${state.year}`,old,value,reason});modal.innerHTML='';render();toast('Исходное значение изменено','Связанные отчеты пересчитаны')}
    else if(ac==='confirm-sync'){modal.innerHTML='';toast('Срезы применены','1С и Pelogas синхронизированы, шаблоны пересчитаны')}
    else if(ac==='confirm-chart'){const kind=$('#chart-kind')?.value,rowId=$('#chart-row')?.value,type=$('#chart-type')?.value,size=$('#chart-size')?.value||'half',r=dataset(kind)?.rows.find(x=>x.id===rowId);if(!r)return;const id='chart-'+Date.now();state.customBlocks[id]={title:r.name,kind,type,size,rowKey:r.code};state.blocks.push(id);modal.innerHTML='';state.view='reports';render();toast('График добавлен',r.name)}
    else if(ac==='confirm-seed-chart'){const sourceBlockId=a.dataset.sourceBlock,rowIndex=Number(a.dataset.rowIndex),id='seedchart-'+Date.now();state.customBlocks[id]={title:$('#seed-chart-title')?.value||'Показатель',kind:'production',type:'seedIndicator',size:$('#seed-chart-size')?.value||'half',sourceBlockId,rowIndex};state.blocks.push(id);modal.innerHTML='';state.view='reports';render();toast('График добавлен')}
    else if(ac==='confirm-schedule'){const recipients=String($('#schedule-recipients')?.value||'').split(',').map(x=>x.trim()).filter(Boolean);if(!recipients.length){toast('Укажите хотя бы один e-mail');return}const freq=$('#schedule-frequency')?.value||'daily',labels={daily:'Каждый день',weekly:'Каждую неделю',monthly:'Каждый месяц'};state.schedules.push({templateId:$('#schedule-template')?.value,recipients,frequency:freq,frequencyLabel:labels[freq],time:$('#schedule-time')?.value||'08:00',format:$('#schedule-format')?.value||'PDF',subject:$('#schedule-subject')?.value||'Управленческий отчет',enabled:true});modal.innerHTML='';state.view='schedules';render();toast('Рассылка настроена',`${labels[freq]} в ${state.schedules.at(-1).time}`)}
  });

  fileInput.addEventListener('change',async()=>{const f=fileInput.files?.[0];if(!f)return;try{const x=JSON.parse(await f.text());if(!Array.isArray(x.blocks))throw 0;const id=x.id||'import-'+Date.now(),t={id,name:x.name||'Импортированный шаблон',description:'Импортирован из JSON',tag:'Импорт',reportTitle:x.reportTitle||x.name,sourceLabel:x.sourceLabel,filters:x.filters||{},blocks:x.blocks,customBlocks:x.customBlocks||{}};state.customTemplates.push(t);if(x.templateOverrides)state.templateOverrides[id]=x.templateOverrides;if(x.seedOverrides)state.seedOverrides[id]=x.seedOverrides;applyTemplate(t);toast('Шаблон принят')}catch(e){toast('Не удалось прочитать JSON')}finally{fileInput.value=''}});

  let dragId=null;function bindDrag(){$$('[data-block][draggable="true"], [data-canvas-block]').forEach(el=>{el.addEventListener('dragstart',()=>dragId=el.dataset.block||el.dataset.canvasBlock);el.addEventListener('dragover',e=>e.preventDefault());el.addEventListener('drop',e=>{e.preventDefault();const to=el.dataset.block||el.dataset.canvasBlock;if(!dragId||dragId===to)return;const a=state.blocks.indexOf(dragId),b=state.blocks.indexOf(to);if(a>=0&&b>=0){const [m]=state.blocks.splice(a,1);state.blocks.splice(b,0,m);render()}})})}
  render();
})();
